config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/new'
  post 'home/new'
    post 'home/index'


  devise_for :users
  get 'images/index'

  get 'images/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'locations#index'

get 'uploads/index'
post 'uploads/index'
get 'uploads/new'
post 'uploads/new'

resources :images, only: [:index, :create]
	# get '/upload' => 'location#upload_create'
	# post 'locations/upload_create'
	# get '/upload' => 'location#upload_new'
	# post 'locations/upload_new'
# post 'locations/index'
resources :locations

get "location/new_release" => 'location#new_release', :as => :new_release

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
		  belongs_to :avatar, polymorphic: true,optional: true
	     mount_uploader :image, ImageUploader
has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/location.rb
class Location < ApplicationRecord
 has_many :images, as: :avatar
	 geocoded_by :address   # can also be an IP address
after_validation :geocode          # auto-fetch coordinates
  accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true

end

app/models/upload.rb
class Upload < ApplicationRecord
	belongs_to :imageable, polymorphic: true,optional: true
		has_attached_file :image, :styles => { :medium => "300x300>",:thumb => "100x100>" }
	
	validates_attachment 	:image, 
				:presence => true,
				:content_type => { :content_type => /\Aimage\/.*\Z/ },
				:size => { :less_than => 1.megabyte }
	  mount_uploader :upload, UploadUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   def index
  end
  def update
  	
  end
  def create
  	
  end
  def show
  	
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
    @image = Image.new
  end


  def create
    @image = Image.new(image_params)

    if @image.save
      render json: { message: "success", fileID: @image.id }, :status => 200
    else
      render json: { error: @image.errors.full_messages.join(',')}, :status => 400
    end
  end
private
  def image_params
    params.require(:image).permit(:avatar)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	  skip_before_action :verify_authenticity_token
	def index
	@locations = Location.all
	# @images = Image.all
       if params[:location].present?
    @locations = Location.near(params[:location], 50, :order => :distance)
  else
    @locations = Location.all
  end
	end
	def new
		@location = Location.new
	end
	def create
		@location = Location.new(location_params)

		if @location.save
			redirect_to @location
		else
			render 'new'
		end
	end
	def show
		@location = Location.find(params[:id])
@images =Image.all
end
	def edit
		@location = Location.find(params[:id])
	end
	def update
		@location= Location.find(params[:id])
		if @location.update(location_params)
			redirect_to @location
		else
			render 'edit'
		end
	end
	def destroy
		@location = Location.find(params[:id])
		@image = Image.find(params[:id])
    @image.destroy
		@location.destroy

		redirect_to locations_path
	end
	def new_release
  respond_to do |format|
    format.html
    format.js
  end
end
	private
	def location_params
		params.require(:location).permit(:name, :address,:description, :latitude,:longitude, images_attributes: [:id, :avatar, :imageable_type, :imageable_id, :_destroy])
	end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
	  skip_before_action :verify_authenticity_token

	def index
     @uploads = Upload.all
         @upload = Upload.new
   end
  #  def new
  #   @upload = Upload.new
  #   # @location = Location.new
  # end
def show
      @upload = Upload.find(params[:id])
end
  def update
    @upload= Upload.find(params[:id])
    if @upload.update(upload_params)
      redirect_to root_path
    else
    end
  end

  def create
    @upload = Upload.new(upload_params)
    if @upload.save
    redirect_to root_path
      # render json: { message: "success", fileID: @upload.id }, :status => 200
    else
      #  you need to send an error header, otherwise Dropzone
      #  will not interpret the response as an error:
      # render json: { error: @upload.errors.full_messages.join(',')}, :status => 400
    end     
  end

  def destroy
    @upload = Upload.find(params[:id])
    @upload.destroy

    redirect_to root_path
  end

  private
  def upload_params
    params.require(:upload).permit(:avatar, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/home/_form.html.erb
<div class="modal-dialog" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close" aria-hidden="true"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title" id="myModalLabel"></h4>
		</div>
		<div class="modal-body">
			<div class="panel panel-black" style="margin-top: -3%; background-color: #1c2a48;">
				<div class="panel-heading" >
					<i><b><h1 style="color: white; text-align: center;">Sing Up</h1></b></i>
				</div>
				<div class="panel-body">
					<div class="well">

						<%= form_for(:user, :url => registration_path(:user),remote: true) do |f| %>

						<div class="field form-group">
							<%= f.label :email, :class => 'control-label col-lg-2' %><br />
							<%= f.email_field :email, autofocus: true, :class => 'form-control' %>
						</div>

						<div class="field">
							<%= f.label :password, :class => 'control-label col-lg-2' %>
							<% if @minimum_password_length %>
							<em>(<%= @minimum_password_length %> characters minimum)</em>
							<% end %><br />
							<%= f.password_field :password, autocomplete: "off", :class => 'form-control' %>
						</div>

						<div class="field">
							<%= f.label :password_confirmation, :class => 'control-label col-lg-2' %><br />
							<%= f.password_field :password_confirmation, autocomplete: "off", :class => 'form-control' %>
						</div>
						<br>
						<div class="actions">
							<%= f.submit "Sign up", :class => 'btn btn-success' %>
						</div>
						<% end %><br>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

app/views/home/_index.html.erb
<div class="modal-dialog" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title" id="myModalLabel"></h4>
		</div>
		<div class="modal-body">
			<div class="panel panel-black" style="margin-top: -3%; background-color: #1c2a48;">
				<div class="panel-heading" >
					<i><b><h1 style="color: white; text-align: center;">Log in</h1></b></i>
				</div>
				<div class="well">
					<%if user_signed_in?%>
					<div class="actions">
						<%#= link_to "Logout", destroy_user_session_path, method: :delete %>
					</div>

					<% else current_user %>
					<%= form_for(:user, :url => session_path(:user), remote: true) do |f| %>
					<div class="field form-group">
						<%= f.label :email, :class => 'control-label col-lg-2'  %><br />
						<%= f.email_field :email, autofocus: true, :class => 'form-control' %>
					</div>

					<div class="field">
						<%= f.label :password, :class => 'control-label col-lg-2' %><br />
						<%= f.password_field :password, autocomplete: "off", :class => 'form-control' %>
					</div>
					<br>
					<div class="field">
						<%= f.check_box :remember_me  %>
						<%= f.label :remember_me %>
					</div>

					<div class="actions ">
						<%= f.submit "Log in", :class => 'btn btn-success'%>
					</div>

					<% end %>

					<% end %>
				</div>
			</div>
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		</div>
	</div>
</div>

app/views/home/index.js.erb
$("#article").html("<%= escape_javascript(render 'index') %>")
$("#myModal").modal("show")

app/views/home/new.html.erb
<%= render 'form' %> 

app/views/home/new.js.erb
$("#article1").html("<%= escape_javascript(render 'form') %>")
$("#myModal").modal("show")

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/images/index.js.erb
// $(".index").html("<%= escape_javascript(render('index')) %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="utf-8">
     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title><%= content_for?(:title) ? yield(:title) : "Place" %></title>
     <%= csrf_meta_tags %>

     <%= stylesheet_link_tag "application", :media => "all" %>
     <%= javascript_include_tag "application" %>
     <%= stylesheet_link_tag    'http://yandex.st/bootstrap/3.1.1/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track' => true %>
     <%= javascript_include_tag 'http://yandex.st/bootstrap/3.1.1/js/bootstrap.min.js', 'data-turbolinks-track' => true %>
</head>
<body>

     <div class="navbar navbar-inverse navbar-static-top">
        <div class="container">
           <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Place</a>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
              <ul class="nav navbar-nav">
                 <li><%if user_signed_in?%></li>

                 <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                 <%else%>
                 <li><%= link_to "login", home_index_path, :remote => true %></li>
                 <li><div id="article"></div></li>

                 <li> <%= link_to "sign up", home_new_path, :remote => true %> </li>
                 <li><div id="article1" ></div></li>
                 <% end%>
                 <% if user_signed_in? %>
                 <li><%= link_to "Logout2", destroy_user_session_path, method: :delete %></li>
                 <% else current_user %>
                 <li><%= link_to "Login2", new_user_session_path, {:remote => true,
                    'data-toggle'=> "modal", 'data-target' => '#login1'} %>
            </li>
            <li><div id="login1" class="modal fade"></div></li>
            <li><%= link_to "sing up2", new_user_registration_path, :remote => true %></li>
            <% end %>
    </ul>
</div>
</div>
</div>
<div class="container">
       <div class="row">
          <div class="col-lg-9">
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
            <%= yield %>
    </div>
</div><!--/row-->
<p>&copy; Company 2018</p>

</div> <!-- /container -->
</body>
</html>

app/views/locations/_form.html.erb
 <div class="panel panel-info">
 	<div class="panel-heading" >

 	</div>
 	<div class="panel-body">
 		<div class="well img-responsive">
 			<%= form_with model: @location, local: true do |form| %>
 			<table class="table-responsive">
 				<div class="form-group">
 					<p>
 						<%=form.label :name, :class => 'control-label col-lg-2' %><br>

 						<%= form.text_field :name, :class => 'form-control' %>
 					</p>

            <p>
            <%=form.label :description, :class => 'control-label col-lg-2' %><br>

    <%= form.text_area :description, :class =>"form-control ckeditor" %>
        <%=form.error_span(:description) %>

          </p>
          <p>

            <%= form.label :address, :class => 'control-label col-lg-2' %>
            <%= form.text_field :address, :class => "form-control", id: "autocomplete", placeholder: "Enter your address", 
             onFocus: "geolocate()"  %>
             <%= form.hidden_field :latitude %>
             <%= form.hidden_field :longitude %>
          </p>
 					<p>
 						<div class="col-md-5" style="margin-left: 25%">
 							<%= form.submit 'submit', :class => 'btn btn-success btn btn-block'  %>
 						</div>
 					</p>
 					<br>
 					<br>
 					<div class="col-md-5" style="margin-left: %">
 						<%= link_to 'Back', locations_path, :class => 'btn btn-info ' %>
 					</div>

 				</div>
 			</table>

 			<% end %>

 		</div>
 	</div>
 </div>
<script>

      var placeSearch, autocomplete;
      var componentForm = {
        street_number: 'short_name',
        route: 'long_name',
        locality: 'long_name',
        administrative_area_level_1: 'short_name',
        country: 'long_name',
        postal_code: 'short_name'
      };

      function initAutocomplete() {
        // Create the autocomplete object, restricting the search to geographical
        // location types.
        autocomplete = new google.maps.places.Autocomplete(
            /** @type {!HTMLInputElement} */(document.getElementById('autocomplete')),
            {types: ['geocode']});

        // When the user selects an address from the dropdown, populate the address
        // fields in the form.
        autocomplete.addListener('place_changed', fillInAddress);
      }

      function fillInAddress() {
        // Get the place details from the autocomplete object.
        var place = autocomplete.getPlace();

        for (var component in componentForm) {
          document.getElementById(component).value = '';
          document.getElementById(component).disabled = false;
        }

        // Get each component of the address from the place details
        // and fill the corresponding field on the form.
        for (var i = 0; i < place.address_components.length; i++) {
          var addressType = place.address_components[i].types[0];
          if (componentForm[addressType]) {
            var val = place.address_components[i][componentForm[addressType]];
            document.getElementById(addressType).value = val;
          }
        }
      }

      // Bias the autocomplete object to the user's geographical location,
      // as supplied by the browser's 'navigator.geolocation' object.
      function geolocate() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var geolocation = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            var circle = new google.maps.Circle({
              center: geolocation,
              radius: position.coords.accuracy
            });
            autocomplete.setBounds(circle.getBounds());
          });
        }
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAN1Y9tstSw1JLgZUHbdL5qL6mRJiY8brw&libraries=places&callback=initAutocomplete"
        async defer></script>


<script >
  $(document).ready(function(){
    $("ckeditor").ckeditor({

    });
  });
</script>

app/views/locations/_index.html.erb
<% @images.each do |image| %>
  <div class="img-thumbnail"><%= image_tag image.avatar.url(:thumb), alt: image.avatar.url(:thumb) %></div>
<% end %>

app/views/locations/edit.html.erb
<div class="col-md-10">
	
	<div class="well" style="text-align: center;">
		<h1><i>Edit location</i></h1>
	</div>
	<i> 
		<%= render 'form' %>
	</i>
</div>
<div class="col-md-2"> 

	<h3>Nearby locations</h3>
	<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>
</div>
<script>

      var placeSearch, autocomplete;
      var componentForm = {
        street_number: 'short_name',
        route: 'long_name',
        locality: 'long_name',
        administrative_area_level_1: 'short_name',
        country: 'long_name',
        postal_code: 'short_name'
      };

      function initAutocomplete() {
        // Create the autocomplete object, restricting the search to geographical
        // location types.
        autocomplete = new google.maps.places.Autocomplete(
            /** @type {!HTMLInputElement} */(document.getElementById('autocomplete')),
            {types: ['geocode']});

        // When the user selects an address from the dropdown, populate the address
        // fields in the form.
        autocomplete.addListener('place_changed', fillInAddress);
      }

      function fillInAddress() {
        // Get the place details from the autocomplete object.
        var place = autocomplete.getPlace();

        for (var component in componentForm) {
          document.getElementById(component).value = '';
          document.getElementById(component).disabled = false;
        }

        // Get each component of the address from the place details
        // and fill the corresponding field on the form.
        for (var i = 0; i < place.address_components.length; i++) {
          var addressType = place.address_components[i].types[0];
          if (componentForm[addressType]) {
            var val = place.address_components[i][componentForm[addressType]];
            document.getElementById(addressType).value = val;
          }
        }
      }

      // Bias the autocomplete object to the user's geographical location,
      // as supplied by the browser's 'navigator.geolocation' object.
      function geolocate() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var geolocation = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            var circle = new google.maps.Circle({
              center: geolocation,
              radius: position.coords.accuracy
            });
            autocomplete.setBounds(circle.getBounds());
          });
        }
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAN1Y9tstSw1JLgZUHbdL5qL6mRJiY8brw&libraries=places&callback=initAutocomplete"
        async defer></script>

app/views/locations/index.html.erb
 <h1>Listing location</h1>
<div class="table-responsive">
<table class="table table-hover table-inverse">
        <thead>
             <tr>
                <th>Name:</th>
                <th>address:</th>
                <th>description:</th>
                <th>show:</th>
                <th>edit:</th>
                <th>delete:</th>
          </tr>
    </thead>
    <tbody>
      <% @locations.each do |location| %>
      <tr>
          <td><%= location.name %></td>
          <td><%= location.address %></td>
          <td><%= location.description %></td>
          <td><%= link_to 'Show', location_path(location), :class => 'btn btn-success ' %></td>
          <td><%= link_to 'Edit', edit_location_path(location), :class => 'btn btn-info ' %></td>
          <td><%= link_to 'Destroy', location_path(location),
              method: :delete,
              data: { confirm: 'are you sure'}, :class => 'btn btn-danger ' %></td>
      </tr>
        <% end %>
  </tbody>
</table>
</div>
<td><%= link_to 'New location', new_location_path, :class => 'btn btn-primary '%></td>

app/views/locations/index.js.erb
$(".index").html("<%= escape_javascript(render('index')) %>")

app/views/locations/new.html.erb
<div class="well" style="text-align: center;">
<h1><i>location Registration Form</i></h1>
</div>
 <i>
<%= render 'form' %> 
</i>

app/views/locations/new_release.html.erb
<div class="modal-header">
   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
   <h3 id="myModalLabel">Modal header</h3>
 </div>
 <div class="modal-body">
<%= location.description %> </div>
 <div class="modal-footer">
   <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
 </div>

app/views/locations/new_release.js.erb
$("#modal-window").html("<%= escape_javascript(render 'location/new_release') %>");

app/views/locations/show.html.erb
	
<div class="col-md-10">
				<%= link_to 'Back', locations_path, :class => 'btn btn-info ' %>
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h1>location details</h1>
		</div>
		<div class="well">
			<strong> Name:</strong><br>
			<%= @location.name %>
			<br>
			<br>
			<strong> address:</strong><br>
			<%= @location.address %>
			<br>
			<br>
			<strong> description:</strong><br>
			<div>
				<% if @location.description.length > 0 %>
				<%= truncate(@location.description, length: 250) %>
				<a type="button" class="read-more-#{@location.id}" href="#test_modal" data-toggle="modal">...read more</a>

			<div class="modal fade img-responsive" id="test_modal" style="width: 60%; height: 400px; margin-left: 21%; margin-top: 8%;">
  <div class="modal">
    <a class="close" data-dismiss="modal">&times;</a>
    <h3></h3>
  </div>
  <div class="modal-body" style="color: black; background-color: white;">
				<div class="panel panel-primary">
		
					<div class="panel-body">
						
				<%= @location.description %>
					</div>
				
				</div>
				<script>
					$('.read-more-<%= @location.id %>').on('click', function(e) {
						e.preventDefault()
						$(this).parent().html('<%= escape_javascript @location.description %>')
					})
				</script>
				<% else %>
				<%= @location.description %>
				<% end %>
    <a href="#" class="btn btn-primary" data-dismiss="modal" style="margin-left: 47%
    ">Close</a>
				</div>
</div>
				<br>
				<br>
				<h1>My Images</h1>
				<%= form_for(Image.new, html: { multipart: true, class: "dropzone"}) do |f|  %>
				<div class="fallback">
					<%= f.file_field :avatar %><br>
					<%= f.submit "Upload my Avatar" %>
				</div>
				<% end %>
				<div class="index">
					<%= render "index" %>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="col-md-2"> 
	<h3>Nearby locations</h3>
	<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>
</div>